### ISSUE TITLE
How do you do a dollar sign in PyPEG2?

### ISSUE THREAD

**Issue by enjoysmath** [Osso/pypeg#1]
As you know you can't simpy do:

dollar = RegEx(r'\$')

I've also tried in place of r'\$' the following: '\$', '\\$', r'\\$'.

It says Expecting '\$' at a certain position when parse() is called (replace @ with any of the above):
```
￼ File "C:\Users\FruitfulApproach\Desktop\bananacats\BananaCatsEditor\engine\grammar.py", line 53, in <module>
  s = parse('$\int a$', InlineFormula)
File "c:\Python36-32\Lib\site-packages\pypeg2\__init__.py", line 667, in parse
  t, r = parser.parse(text, thing)
File "c:\Python36-32\Lib\site-packages\pypeg2\__init__.py", line 794, in parse
  raise r

Syntax Error: expecting match on @: <string>, line 1, pos 1 in file c:\Python36-32\Lib\site-packages\pypeg2\__init__.py, line 794
raise r
```

**Comment by Osso** [comment]
If you just want a $, you could do dollar = Literal('$') or if you need it in a regexp you escape like any other regexps.

This is just my dev repo. I am the only one looking at it. There's more people at the official repo on https://bitbucket.org/fdik/pypeg/issues?status=new&status=open
